apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dns-client
  template:
    metadata:
      labels:
        app: dns-client
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.20.0.53
      containers:
        - name: client
          image: busybox:1.37.0
          command:
            - sh
            - -c
          args:
            - while true; do nslookup -type=A www.microsoft.com; sleep 0.2; done
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi